# Generated by Django 4.0.5 on 2022-12-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.TextField(default='', max_length=900, null=True),
        ),
    ]
